version: "3.7"

x-web-volumes: &web-volumes
  - .:/app:cached
  - bundle_cache:/bundle_cache

x-web-environment: &web-environment
  - BUNDLE_PATH=/bundle_cache
  - GEM_HOME=/bundle_cache
  - GEM_PATH=/bundle_cache
  - PORT=4000

x-aws-vault-environment: &aws-vault-environment
  - AWS_VAULT
  - AWS_DEFAULT_REGION
  - AWS_REGION
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
  - AWS_SESSION_TOKEN
  - AWS_SECURITY_TOKEN
  - AWS_SESSION_EXPIRATION

services:
  web:
    build: .
    volumes: *web-volumes
    ports:
      - "4000:4000"
    environment: *web-environment
    command: bash -c "bundle exec rackup"

  bundle_cache:
    image: busybox
    volumes:
      - bundle_cache:/bundle_cache

volumes:
  bundle_cache:

services:
  remote:
    build: ./docker/remote
    entrypoint: ""
    environment: *aws-vault-environment
    volumes:
      - ./docker/remote:/app:cached
      - .aws:/root/.aws
