version: "3.9"

x-web-volumes: &web-volumes
  - .:/app:cached
  - bundle_cache:/bundle_cache

x-web-environment: &web-environment
  - BUNDLE_PATH=/bundle_cache
  - GEM_HOME=/bundle_cache
  - GEM_PATH=/bundle_cache
  - PORT=4000

services:
  web:
    build: .
    volumes: *web-volumes
    ports:
      - "4000:4000"
    environment: *web-environment
    command: bash -c "bundle install; bundle exec rackup"

  bundle_cache:
    image: busybox
    volumes:
      - bundle_cache:/bundle_cache

  image:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/remote/Dockerfile
      args:
        ECS_CLUSTER_NAME: ${ECS_CLUSTER_NAME}
        ECS_TASK_ID: ${ECS_TASK_ID}
        AWS_REGION: ${AWS_REGION}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

    volumes:
      - ./docker/remote:/app/:cached
      - .aws:/app/.aws

volumes:
  bundle_cache:
